### ISSUE TITLE
Please upgrade vulnerable package

### ISSUE THREAD

**Issue by zsoltfeher** [scaleddomains/ScaledDomains.Extensions.Caching.MySql#27]
Hi,

It looks like this library has an indirect denedency on a vulnerable package (System.Drawing.Common@4.6.0) with the path:
ScaledDomains.Extensions.Caching.MySql@1.0.0 > MySql.Data@8.0.21 > System.Security.Permissions@4.6.0 > System.Windows.Extensions@4.6.0 > System.Drawing.Common@4.6.0

Please upgrade to a newer version.
Thank you.

**Comment by attilaersek** [comment]
Thank you @zsoltfeher ! #26 should solve it.
